### PR TITLE
Remove built-in injection

### PR DESCRIPTION
**Pull request by thekid**
This pull request removes support for `@inject` built into the command runner, which was limited to database connections, logger categories and property files. Users may chose to use `xp-forge/inject` or other libraries to recreate this. See also #4 

*This would bump the major version - **9.0.0** at the time of writing*.

### CODE REVIEW

**Comment by thekid** [comment]
Maybe a `seven` branch should be created from which bugfix releases could be made.

**Comment by kiesel** [comment]
:-1: 

What about making this implementation use the one of `xp-forge/inject` to do it. Removing this facility, though it being a non-elegant solution, will make it hard for people to keep up-to-date with this library.

**Comment by thekid** [comment]
> What about making this implementation use the one of `xp-forge/inject` to do it

That would also be an idea, but:
- I'm against supporting the old hardcoded "logger, properties, database connection" standard; especially it being implemented with the global singletons (*shudder*)
- I don't want to force a specific injector on people (which both old implementation and this suggestion do)
- I want to keep dependencies as small as possible

However, a bridging technology could be included which would call the old methods if necessary. People would need to include a trait (and possibly even a "BC" library).

**Comment by thekid** [comment]
> However, a bridging technology could be included [...in form of a...] "BC" library

This would be an example: https://github.com/thekid/command-bc (although it would be moved to xp-framework and potentially renamed before being released officially). Retaining BC goes as follows:

Add dependency:

``` sh
$ composer require thekid/command-bc
```

Use the trait supplied in this package:

``` php
<?php namespace com\example\cmd;

class Test extends \util\cmd\Command {
  use \util\cmd\MethodInjection;        // <-- Add this line!

  #[@inject(name= 'sources')]
  public function useConfig(Properties $prop) {
    // ...
  }
}
```

**Done!**

**Comment by kiesel** [comment]
The trait looks good. But what about including it in the original package instead of creating yet another dependency? It could be completely optional, discouraged even, but still there to use. Possibly, we'd need to make it more defensive about what classes are available and what to inject, then, but still...

**Comment by thekid** [comment]
> But what about including it in the original package 

Yep, an even better idea. It could still be phased out at a later point.

**Comment by thekid** [comment]
Updated to newest `master`. Will add trait as described above, adding that to 8.2.0 by default, announce deprecation and removing it alltogether in 9.0.0

**Pull request merged**
